# Generated by Django 4.0.6 on 2022-07-21 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_rename_wholelist_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
